/**
 * Shared Thai UI label dictionary. Use these constants in BOTH apps so wording
 * stays identical (the orchestration plan's #1 drift risk is mismatched labels).
 */
export const TH = {
  app: {
    name: "ระบบขอที่จอดรถ ป.ป.ช.",
    adminName: "ระบบจัดการคำขอที่จอดรถ (ผู้ดูแล)",
    userName: "ระบบบันทึกคำขอที่จอดรถ",
  },
  entity: {
    parkingRequest: "คำขอที่จอดรถ",
    officialLetter: "หนังสือราชการ",
    officialLetterNo: "เลขหนังสือ",
    department: "สำนัก/หน่วยงาน",
    requestingDepartment: "สำนัก/หน่วยงานผู้ขอ",
    requestedDate: "วันที่ต้องการใช้ที่จอดรถ",
    requestedLocation: "สถานที่ที่ต้องการ",
    carsCount: "จำนวนรถ",
    licensePlate: "ป้ายทะเบียน",
    status: "สถานะ",
    attachment: "ไฟล์แนบ",
    completionPhoto: "รูปถ่ายส่งงาน",
    cancellationReason: "เหตุผลการยกเลิก",
    assignedTo: "ผู้รับผิดชอบ",
    requestNo: "เลขที่คำขอ",
    letterDate: "วันที่หนังสือ",
    receivedDate: "วันที่รับหนังสือ",
    subject: "เรื่อง",
    contactName: "ผู้ประสานงาน",
    contactPhone: "เบอร์โทร",
    purpose: "เหตุผล/รายละเอียด",
    note: "หมายเหตุเพิ่มเติม",
    adminNote: "หมายเหตุภายใน",
    startTime: "เวลาเริ่ม",
    endTime: "เวลาสิ้นสุด",
    priority: "ความเร่งด่วน",
    datePattern: "ประเภทการเลือกวัน",
  },
  action: {
    create: "สร้างคำขอใหม่",
    recordLetter: "บันทึกหนังสือขอที่จอดรถ",
    saveDraft: "บันทึกแบบร่าง",
    submit: "ส่งคำขอ",
    edit: "แก้ไข",
    delete: "ลบ",
    cancel: "ยกเลิก",
    confirm: "ยืนยัน",
    close: "ปิด",
    assign: "มอบหมายงาน",
    reassign: "มอบหมายใหม่",
    acceptJob: "รับงาน",
    startJob: "เริ่มดำเนินการ",
    completeJob: "ส่งงานพร้อมรูปถ่าย",
    cancelJob: "ยกเลิกงานพร้อมเหตุผล",
    uploadAttachment: "แนบไฟล์",
    attachCompletionPhoto: "แนบรูปส่งงาน",
    compressImage: "บีบอัดรูปภาพ",
    uploading: "กำลังอัปโหลด",
    completeWithPhotos: "ส่งงานเสร็จสมบูรณ์",
    viewImage: "ดูรูปภาพ",
    uploadFailed: "อัปโหลดไม่สำเร็จ",
    completionUploadFailed: "อัปโหลดรูปส่งงานไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
    requireCompletionPhoto: "กรุณาแนบรูปอย่างน้อย 1 รูป",
    viewDetail: "ดูรายละเอียด",
    export: "ส่งออกข้อมูล",
    search: "ค้นหา",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    back: "ย้อนกลับ",
    save: "บันทึก",
  },
  security: {
    acknowledge: "รับทราบ",
    acknowledgeJob: "รับทราบงานนี้",
    acknowledged: "รับทราบแล้ว พร้อมดำเนินการ",
    startArranging: "เริ่มจัดที่จอด",
    submitWork: "ส่งงาน",
    confirmSubmitWork: "ยืนยันส่งงาน",
    workDone: "ทำงานเรียบร้อยแล้ว",
  },
  comms: {
    pendingApproval: "รออนุมัติ",
    inSecurity: "ดำเนินการรปภ.",
    awaitingVerification: "รอตรวจงานรปภ.",
    verified: "ยืนยันแล้ว",
    needsAction: "ต้องจัดการ",
    awaitingTag: "รอสื่อสารตรวจสอบ",
    verifiedTag: "ยืนยันโดยสื่อสารแล้ว",
    markUnderReview: "รับเข้าตรวจสอบ",
    approve: "อนุมัติคำขอ",
    reject: "ไม่อนุมัติ",
    verifyCompletion: "ยืนยันงานสำเร็จ",
    approveHint: "อนุมัติแล้วงานจะไปที่ รปภ. ให้แนบหนังสือราชการก่อนอนุมัติ",
    needOfficialLetter: "ต้องแนบไฟล์หนังสือราชการก่อนอนุมัติ",
    approvedSuccess: "อนุมัติแล้ว ส่งงานไป รปภ.",
    verifiedSuccess: "ยืนยันงานสำเร็จแล้ว",
    missingLetter: "ยังไม่แนบหนังสือ",
    recordLetter: "บันทึกหนังสือ",
    recordAndSend: "บันทึกและส่งให้ รปภ.",
    recordHint: "บันทึกโดยสื่อสารจะข้ามขั้นตอนอนุมัติและส่งงานไป รปภ. ทันที",
    recordSuccess: "บันทึกแล้ว ส่งงานไป รปภ. ทันที",
    specialModesTitle: "โหมดพิเศษ",
    specialModesHint:
      "ตั้งค่าระดับระบบ — เปิดแล้วจะทำงานตลอดจนกว่าจะมีคนมาปิด (ปิดหน้าหรือเปิดใหม่ก็ยังเปิดอยู่)",
    serverLevelBadge: "ระดับระบบ",
    serverActiveNote: "โหมดเปิดอยู่บนเซิร์ฟเวอร์ — ต้องกดปิดเองเท่านั้น",
    autoApproveTitle: "อนุมัติคำขออัตโนมัติ",
    autoApproveDesc: "คำขอที่รออนุมัติและคำขอใหม่จะอนุมัติทันที (ต้องมีไฟล์หนังสือ)",
    autoApproveWarning:
      "หากเปิดไว้ ต้องรับผิดชอบหากหนังสือหรือข้อมูลผิดพลาด — อาจถูกดำเนินการโดยไม่ตรวจสอบ",
    autoVerifyTitle: "ยืนยันงาน รปภ. อัตโนมัติ",
    autoVerifyDesc: "เมื่อ รปภ. ส่งงานเสร็จ ระบบจะยืนยันแทนสื่อสารทันที",
    autoVerifyWarning:
      "หากเปิดไว้ ต้องรับผิดชอบหากงานยังไม่ถูกต้อง — อาจถูกปิดงานโดยไม่ตรวจสอบ",
    modeOn: "เปิด",
    modeOff: "ปิด",
  },
  admin: {
    needsAction: "ต้องจัดการ",
    underReview: "รอตรวจสอบ",
    unassigned: "รอมอบหมาย",
    inProgress: "กำลังดำเนินการ",
    completed: "เสร็จแล้ว",
    workPanelTitle: "งานที่ต้องจัดการ",
  },
  reports: {
    trendTitle: "แนวโน้มคำขอและจำนวนรถ",
    trendHint: "เลือกดูแบบรายวัน รายสัปดาห์ หรือรายเดือน ตามวันที่รับหนังสือ",
    byDay: "สรุปรายวัน (วันที่รับหนังสือ)",
    byWeek: "สรุปรายสัปดาห์ (วันที่รับหนังสือ)",
    byMonth: "สรุปรายเดือน (วันที่รับหนังสือ)",
  },
  nav: {
    dashboard: "แดชบอร์ด",
    requests: "คำขอที่จอดรถ",
    calendar: "ปฏิทิน",
    assignments: "การมอบหมายงาน",
    departments: "สำนัก/หน่วยงาน",
    locations: "สถานที่จอดรถ",
    users: "ผู้ใช้งาน",
    reports: "รายงาน",
    settings: "ตั้งค่า",
    activityLogs: "บันทึกกิจกรรม",
    importLogs: "บันทึกการนำเข้า",
    officerDashboard: "หน้าหลักบันทึกหนังสือ",
    officerDashboardShort: "หน้าหลัก",
    officerRequests: "รายการคำขอทั้งหมด",
    officerRequestsShort: "รายการ",
    recordLetterShort: "บันทึก",
    securityDashboard: "หน้าหลักงาน รปภ.",
    securityParkingCalendar: "ปฏิทินจอดรถ",
    parkingCalendar: "ปฏิทินจอดรถ",
    parkingCalendarShort: "ปฏิทิน",
    commsRecordLetterShort: "บันทึก",
    myRequests: "คำขอของฉัน",
    jobs: "งานที่ได้รับ",
    history: "ประวัติการทำงาน",
  },
  dashboard: {
    totalRequests: "คำขอทั้งหมด",
    pending: "รอดำเนินการ",
    inProgress: "กำลังดำเนินการ",
    completed: "เสร็จสมบูรณ์",
    cancelled: "ยกเลิก",
    carsToday: "จำนวนรถที่ขอวันนี้",
    lettersToday: "จำนวนหนังสือวันนี้",
    unassigned: "งานที่ยังไม่ได้มอบหมาย",
    byStatus: "คำขอแยกตามสถานะ",
    byDepartment: "คำขอแยกตามสำนัก",
    byDate: "คำขอแยกตามวันที่",
    carsByDate: "จำนวนรถแยกตามวันที่",
    recentRequests: "คำขอล่าสุด",
  },
  state: {
    loading: "กำลังโหลด...",
    empty: "ยังไม่มีข้อมูล",
    error: "เกิดข้อผิดพลาด",
    noResults: "ไม่พบรายการที่ค้นหา",
    saving: "กำลังบันทึก...",
    saved: "บันทึกเรียบร้อยแล้ว",
    required: "กรุณากรอกข้อมูลให้ครบถ้วน",
  },
  auth: {
    username: "ชื่อผู้ใช้",
    password: "รหัสผ่าน",
    signIn: "เข้าสู่ระบบ",
    signingIn: "กำลังเข้าสู่ระบบ...",
    invalidCredentials: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    selectRole: "เลือกบทบาทการใช้งาน",
    noAccess: "บัญชีของคุณไม่มีสิทธิ์เข้าใช้งานส่วนนี้",
    inactive: "บัญชีนี้ถูกระงับการใช้งาน",
  },
} as const;
