/**
 * Shared Thai UI label dictionary. Use these constants in BOTH apps so wording
 * stays identical (the orchestration plan's #1 drift risk is mismatched labels).
 */
export const TH = {
  app: {
    name: "ระบบขอที่จอดรถ ป.ป.ช.",
    adminName: "ระบบจัดการคำขอที่จอดรถ (ผู้ดูแล)",
    userName: "ระบบบันทึกคำขอที่จอดรถ",
  },
  entity: {
    parkingRequest: "คำขอที่จอดรถ",
    officialLetter: "หนังสือราชการ",
    officialLetterNo: "เลขหนังสือ",
    department: "สำนัก/หน่วยงาน",
    requestingDepartment: "สำนัก/หน่วยงานผู้ขอ",
    requestedDate: "วันที่ต้องการใช้ที่จอดรถ",
    requestedLocation: "สถานที่ที่ต้องการ",
    carsCount: "จำนวนรถ",
    licensePlate: "ป้ายทะเบียน",
    status: "สถานะ",
    attachment: "ไฟล์แนบ",
    completionPhoto: "รูปถ่ายส่งงาน",
    cancellationReason: "เหตุผลการยกเลิก",
    assignedTo: "ผู้รับผิดชอบ",
    requestNo: "เลขที่คำขอ",
    letterDate: "วันที่หนังสือ",
    receivedDate: "วันที่รับหนังสือ",
    subject: "เรื่อง",
    contactName: "ผู้ประสานงาน",
    contactPhone: "เบอร์โทร",
    purpose: "เหตุผล/รายละเอียด",
    note: "หมายเหตุเพิ่มเติม",
    adminNote: "หมายเหตุภายใน",
    startTime: "เวลาเริ่ม",
    endTime: "เวลาสิ้นสุด",
    priority: "ความเร่งด่วน",
    datePattern: "ประเภทการเลือกวัน",
  },
  action: {
    create: "สร้างคำขอใหม่",
    recordLetter: "บันทึกหนังสือขอที่จอดรถ",
    saveDraft: "บันทึกแบบร่าง",
    submit: "ส่งคำขอ",
    edit: "แก้ไข",
    delete: "ลบ",
    cancel: "ยกเลิก",
    confirm: "ยืนยัน",
    close: "ปิด",
    assign: "มอบหมายงาน",
    reassign: "มอบหมายใหม่",
    acceptJob: "รับงาน",
    startJob: "เริ่มดำเนินการ",
    completeJob: "ส่งงานพร้อมรูปถ่าย",
    cancelJob: "ยกเลิกงานพร้อมเหตุผล",
    uploadAttachment: "แนบไฟล์",
    attachCompletionPhoto: "แนบรูปส่งงาน",
    compressImage: "บีบอัดรูปภาพ",
    uploading: "กำลังอัปโหลด",
    completeWithPhotos: "ส่งงานเสร็จสมบูรณ์",
    viewImage: "ดูรูปภาพ",
    uploadFailed: "อัปโหลดไม่สำเร็จ",
    completionUploadFailed: "อัปโหลดรูปส่งงานไม่สำเร็จ กรุณาลองใหม่อีกครั้ง",
    requireCompletionPhoto: "กรุณาแนบรูปอย่างน้อย 1 รูป",
    viewDetail: "ดูรายละเอียด",
    export: "ส่งออกข้อมูล",
    search: "ค้นหา",
    login: "เข้าสู่ระบบ",
    logout: "ออกจากระบบ",
    back: "ย้อนกลับ",
    save: "บันทึก",
  },
  security: {
    acknowledge: "รับทราบ",
    acknowledgeJob: "รับทราบงานนี้",
    acknowledged: "รับทราบแล้ว พร้อมดำเนินการ",
    startArranging: "เริ่มจัดที่จอด",
    submitWork: "ส่งงาน",
    confirmSubmitWork: "ยืนยันส่งงาน",
    workDone: "ทำงานเรียบร้อยแล้ว",
  },
  nav: {
    dashboard: "แดชบอร์ด",
    requests: "คำขอที่จอดรถ",
    calendar: "ปฏิทิน",
    assignments: "การมอบหมายงาน",
    departments: "สำนัก/หน่วยงาน",
    locations: "สถานที่จอดรถ",
    users: "ผู้ใช้งาน",
    reports: "รายงาน",
    settings: "ตั้งค่า",
    activityLogs: "บันทึกกิจกรรม",
    importLogs: "บันทึกการนำเข้า",
    officerDashboard: "หน้าหลักเจ้าหน้าที่รับหนังสือ",
    securityDashboard: "หน้าหลักงาน รปภ.",
    myRequests: "คำขอของฉัน",
    jobs: "งานที่ได้รับ",
    history: "ประวัติการทำงาน",
  },
  dashboard: {
    totalRequests: "คำขอทั้งหมด",
    pending: "รอดำเนินการ",
    inProgress: "กำลังดำเนินการ",
    completed: "เสร็จสมบูรณ์",
    cancelled: "ยกเลิก",
    carsToday: "จำนวนรถที่ขอวันนี้",
    lettersToday: "จำนวนหนังสือวันนี้",
    unassigned: "งานที่ยังไม่ได้มอบหมาย",
    byStatus: "คำขอแยกตามสถานะ",
    byDepartment: "คำขอแยกตามสำนัก",
    byDate: "คำขอแยกตามวันที่",
    carsByDate: "จำนวนรถแยกตามวันที่",
    recentRequests: "คำขอล่าสุด",
  },
  state: {
    loading: "กำลังโหลด...",
    empty: "ยังไม่มีข้อมูล",
    error: "เกิดข้อผิดพลาด",
    noResults: "ไม่พบรายการที่ค้นหา",
    saving: "กำลังบันทึก...",
    saved: "บันทึกเรียบร้อยแล้ว",
    required: "กรุณากรอกข้อมูลให้ครบถ้วน",
  },
  auth: {
    username: "ชื่อผู้ใช้",
    password: "รหัสผ่าน",
    signIn: "เข้าสู่ระบบ",
    signingIn: "กำลังเข้าสู่ระบบ...",
    invalidCredentials: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    selectRole: "เลือกบทบาทการใช้งาน",
    noAccess: "บัญชีของคุณไม่มีสิทธิ์เข้าใช้งานส่วนนี้",
    inactive: "บัญชีนี้ถูกระงับการใช้งาน",
  },
} as const;
